apiVersion: v1
kind: Service
metadata:
  name: substrate-service
  labels:
    app: substrate-platform
spec:
  selector:
    app: substrate-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
